algorithm: rankup
save_dir: ./saved_models/classic_cv
save_name: rankup_cyclone_normalized
resume: False
load_path: ./saved_models/classic_cv/rankup_cyclone_normalized/latest_model.pth
overwrite: True
use_tensorboard: False
use_wandb: True
wandb_mode: online
wandb_online_logging:
  project: DD2610Project
  name: classic_cv_rankup_cyclone_normalized

epoch: 100
num_train_iter: 50000
num_eval_iter: 1000
num_log_iter: 50
num_labels: 250
batch_size: 32
eval_batch_size: 64
ema_m: 0.999
uratio: 7
arc_loss_ratio: 0.2
arc_ulb_loss_ratio: 1.0
hard_label: True
T: 0.5
p_cutoff: 0.95
optim: SGD
lr: 0.003
momentum: 0.9
weight_decay: 0.001
layer_decay: 1.0
amp: False
clip_grad: 0.0
use_cat: True
criterion: l1
net: wrn_28_2
net_from_name: False

# --- CRITICAL PATHS ---
data_dir: ./archive      # Points to where you extracted the zip
dataset: cyclone         # Matches the key in get_dataset.py
train_sampler: RandomSampler
num_workers: 4           # Keep 0 for Windows! Change to 4 for Google Cloud.
crop_ratio: 0.875
img_size: 64
# ----------------------

seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10002
dist_backend: nccl